### ISSUE TITLE
Support Sentinel-2 Level-2A data (with AUX bands) as collection

### ISSUE THREAD

**Issue by griembauer** [Open-EO/openeo-grassgis-driver#105]
Currently, a Sentinel-2 collection is expected to have exactly 13 bands: https://github.com/Open-EO/openeo-grassgis-driver/blob/master/src/openeo_grass_gis_driver/collection_information.py#L209

This however only applies to Level-1C data, as Level-2A does not have a B10 anymore. 
Instead, Level-2A data contains additional auxiliary bands (AOT, SCL, TCI, WVP). It would be required to

- allow for Sentinel-2 scenes to contain only 12 bands
- decide on whether to support the auxiliary bands including band metadata

**Comment by metzm** [comment]
Should be fixed with #107.

**Comment by jonas-eberle** [comment]
@metzm But the if clause (number of bands equals 13) seems to be wrong for L2A datasets: 
https://github.com/Open-EO/openeo-grassgis-driver/blob/master/src/openeo_grass_gis_driver/collection_information.py#L209

Also the following part seems to be strange (static setting of Sentinel-2 properties):
https://github.com/Open-EO/openeo-grassgis-driver/blob/master/src/openeo_grass_gis_driver/collection_information.py#L258-L260

In addition, band S2_10 (cirrus) is only available in Sentinel-2 L1C but not in L2A. 

Is this band information in the collection response relevant for openEO?

**Comment by metzm** [comment]
The endpoint `/collections/{collection_id}` now dynamically reports all bands present in the actual collection (GRASS strds), auxiliary bands like AOT, SCL, TCI, WVP are also reported if present.

This list of band names is relevant for openEO because some processes like `array_element`, used e.g. by `reduce_dimension` (needed e.g. to calculate normalized differences), may refer to bands either by index or by label. If referred to by index, the order of band names matters, but might be difficult to determine depending on preceding processing steps, particularly `filter_bands`: the order of band names can not be determined when constructing an openEO process graph because the corresponding raster datacube (GRASS strds) might not yet exist.

**Comment by metzm** [comment]
Fixed.
